---
title: "Schema boards: main contrasts"
output:
  html_document:
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Setup: load data, define variables, etc

```{r load-data-define-variables}

rm(list=ls())

source('./scripts/utils/load_all_libraries.R')

qc_filter <- T

plot_normality <- T
plot_mouse_clicks <- F
plot_fits_near_far <- F

source('./scripts/utils/load_transform_data.R')

qc_table <- import('./results/qc_check_sheets/qc_table.csv')

if (qc_filter){
        
        qc_pass_ptp <- qc_table %>%
                filter(!qc_fail_overall) %>%
                select(ptp) %>% .[[1]]
        
        
        data_summary <- data_summary %>%
                filter(ptp %in% qc_pass_ptp)
        long_data <- long_data %>%
                filter(ptp %in% qc_pass_ptp) 
        mean_by_rep_long_all_types <- mean_by_rep_long_all_types %>%
                filter(ptp %in% qc_pass_ptp)
        
}

## BF test against 0 
reportBF = function(x, digits){
        round(as.numeric(as.vector(x)), digits)
}

```

# Normality checks

## Block 2

```{r block-2-normality-checks}
if (plot_normality){
       # Density plot
data_summary %>%
        # filter(hidden_pa_img_type == 'near_far_combined') %>%
        ggplot(aes(x=block_2_mouse_error_mean,
                   y = ..density..)) +
        geom_histogram() +
        geom_density(lwd = 1,
                     color = 'red') +
        facet_wrap(~hidden_pa_img_type) +
        ggtitle('Block 2, RAW: Histogram and Density')

# QQ Plot

data_summary %>%
        
        # filter(hidden_pa_img_type == 'near_far_combined') %>%
        ggqqplot(x = 'block_2_mouse_error_mean') +
        ggtitle('Block 2, RAW: QQ Plots') +
        facet_wrap(~hidden_pa_img_type) 
}


```

```{r log-transformations}
if (plot_normality){
        
    # Density plot
data_summary %>%
        ggplot(aes(x=block_2_mouse_error_mean_LOG,
                   y = ..density..)) +
        geom_histogram() +
        geom_density(lwd = 1,
                     color = 'red') +
        facet_wrap(~hidden_pa_img_type) +
        ggtitle('Block 2, LOG: Histogram and Density')

# QQ Plot

data_summary %>%
        ggqqplot(x = 'block_2_mouse_error_mean_LOG') +
        ggtitle('Block 2, LOG: QQ Plots') +
        facet_wrap(~hidden_pa_img_type)

}

```


# Block 2 mean performance:

## Compare conditions, across PAs:

```{r block-2-conditions, fig.width=7}

data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        ggplot(aes(x=condition,
                   y=block_2_mouse_error_mean,
                   fill=condition)) +
        geom_violin(alpha = 0.2) +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_point(alpha = 0.2) +
        # geom_jitter(height = 0,
        #             width = 0.06,
        #             alpha = 0.3) +
        geom_line(aes(group=ptp),
                  alpha = 0.1) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2, comparing conditions') +
        ylab('Block 2 error') + 
        xlab('') +
        theme(legend.position = '')

```

```{r block-2-LOG-conditions}

data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        ggplot(aes(x=condition,
                   y=block_2_mouse_error_mean_LOG,
                   fill=condition)) +
        geom_violin(alpha = 0.2) +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_point(alpha = 0.2) +
        # geom_jitter(height = 0,
        #             width = 0.06,
        #             alpha = 0.3) +
        geom_line(aes(group=ptp),
                  alpha = 0.1) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2 LOG, comparing conditions')

```

## 2_2 vs 4_2

### Plot:

```{r 2-2-vs-4-2, fig.width=3, fig.height=4}

data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean) %>% 
        mutate(schema_2_2_minus_4_2 = schema_2_2 - schema_4_2) %>% 
        
        ggplot(aes(x='difference',
                   y=schema_2_2_minus_4_2)) +
        geom_violin() +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_jitter(height = 0,
                    width = 0.06,
                    alpha = 0.3) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2, schema-2-2 vs schema-4-2') +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        ylab('Schema-L minus Schema-C') +
        xlab('')

```

```{r schema-2-2-vs-schema-4-2-LOG, fig.width=3, fig.height=4}

data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean_LOG) %>% 
        mutate(schema_2_2_minus_4_2 = schema_2_2 - schema_4_2) %>% 
        
        ggplot(aes(x='difference',
                   y=schema_2_2_minus_4_2)) +
        geom_violin() +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_jitter(height = 0,
                    width = 0.06,
                    alpha = 0.3) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2, schema-2-2 vs schema-4-2 LOG') +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        ylab('Schema-L minus Schema-C LOG') +
        xlab('')

```


### Bayes Factor

```{r bf-analysis-schema-2-2-vs-schema-2-4}

data_for_bf_2_2_vs_4_2 <- data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean) %>% 
        mutate(schema_2_2_minus_4_2 = schema_2_2 - schema_4_2) %>% 
        select(schema_2_2_minus_4_2) %>% .[[1]]


null_interval <- c(-Inf,Inf)

bf_2_2_vs_4_2 <- reportBF(ttestBF(
        data_for_bf_2_2_vs_4_2,
        nullInterval = null_interval
)[1],4)

# Just get the effect size:
es_2_2_vs_4_2 <- mean(data_for_bf_2_2_vs_4_2) / sd(data_for_bf_2_2_vs_4_2)

```


```{r bf-analysis-schema-2-2-vs-schema-2-4-LOG}

data_for_bf_2_2_vs_4_2_LOG <- data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean_LOG) %>% 
        mutate(schema_2_2_vs_4_2 = schema_2_2 - schema_4_2) %>% 
        select(schema_2_2_vs_4_2) %>% .[[1]]


null_interval <- c(-Inf,Inf)

bf_2_2_vs_4_2_LOG <- reportBF(ttestBF(
        data_for_bf_2_2_vs_4_2_LOG,
        nullInterval = null_interval
)[1],4)

```


## 4_4 vs 4_2

### Plot:

```{r 4-4-vs-4-2, fig.width=3, fig.height=4}

data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean) %>% 
        mutate(schema_4_4_minus_4_2 = schema_4_4 - schema_4_2) %>% 
        
        ggplot(aes(x='difference',
                   y=schema_4_4_minus_4_2)) +
        geom_violin() +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_jitter(height = 0,
                    width = 0.06,
                    alpha = 0.3) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2, schema-4_4 vs schema-4_2') +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        ylab('Schema-L minus Schema-C') +
        xlab('')

```

```{r schema-4_4-vs-schema-4-2-LOG, fig.width=3, fig.height=4}

data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean_LOG) %>% 
        mutate(schema_4_4_minus_4_2 = schema_4_4 - schema_4_2) %>% 
        
        ggplot(aes(x='difference',
                   y=schema_4_4_minus_4_2)) +
        geom_violin() +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_jitter(height = 0,
                    width = 0.06,
                    alpha = 0.3) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2, schema-4-4 vs schema-4-2 LOG') +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        ylab('Schema-L minus Schema-C LOG') +
        xlab('')

```


### Bayes Factor

```{r bf-analysis-schema-4-4-vs-schema-4-2}

data_for_bf_4_4_vs_4_2 <- data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean) %>% 
        mutate(schema_4_4_minus_4_2 = schema_4_4 - schema_4_2) %>% 
        select(schema_4_4_minus_4_2) %>% .[[1]]


null_interval <- c(-Inf,Inf)

bf_4_4_vs_4_2 <- reportBF(ttestBF(
        data_for_bf_4_4_vs_4_2,
        nullInterval = null_interval
)[1],4)

# Just get the effect size:
es_4_4_vs_4_2 <- mean(data_for_bf_4_4_vs_4_2) / sd(data_for_bf_4_4_vs_4_2)

```


```{r bf-analysis-schema-4-4-vs-schema-4-2-LOG}

data_for_bf_4_4_vs_4_2_LOG <- data_summary %>%
        filter(hidden_pa_img_type == 'near_far_combined') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                hidden_pa_img_type),
                    names_from = condition,
                    values_from = block_2_mouse_error_mean_LOG) %>% 
        mutate(schema_4_4_vs_4_2 = schema_4_4 - schema_4_2) %>% 
        select(schema_4_4_vs_4_2) %>% .[[1]]


null_interval <- c(-Inf,Inf)

bf_4_4_vs_4_2_LOG <- reportBF(ttestBF(
        data_for_bf_4_4_vs_4_2_LOG,
        nullInterval = null_interval
)[1],4)

```

## Near vs Far within each condition:

```{r block-2-conditions-near-far, fig.width=7}

data_summary %>%
        filter(!hidden_pa_img_type %in% c('all_pa',
                                          'near_far_combined')) %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                condition),
                    names_from = hidden_pa_img_type,
                    values_from = block_2_mouse_error_mean) %>% 
        mutate(far_minus_near = far - near) %>%
        
        ggplot(aes(x=condition,
                   y=far_minus_near,
                   fill=condition)) +
        geom_violin(alpha = 0.2) +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        # geom_jitter(height = 0,
        #             width = 0.06,
        #             alpha = 0.3) +
        geom_line(aes(group=ptp),
                  alpha = 0.1) +
        geom_point(alpha = 0.2) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2, comparing conditions, Far-Near') +
        geom_hline(yintercept = 0, linetype = 'dashed') +
        theme(legend.position = '') +
        ylab('Far minus Near') +
        xlab('')

```

```{r block-2-LOG-conditions-near-far}

data_summary %>%
        filter(!hidden_pa_img_type %in% c('all_pa',
                                          'near_far_combined')) %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                condition),
                    names_from = hidden_pa_img_type,
                    values_from = block_2_mouse_error_mean_LOG) %>% 
        mutate(far_minus_near = far - near) %>%
        
        ggplot(aes(x=condition,
                   y=far_minus_near,
                   fill=condition)) +
        geom_violin(alpha=0.2) +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        # geom_jitter(height = 0,
        #             width = 0.06,
        #             alpha = 0.3) +
        geom_line(aes(group=ptp),
                  alpha = 0.1) +
        geom_point(alpha = 0.2) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2 LOG, comparing conditions, Far-Near') +
        geom_hline(yintercept = 0, linetype = 'dashed')

```

### Bayes Factor

```{r bayes-analysis-schema-c-far-vs-near}

data_for_bf_schema_6_0_far_vs_near <- data_summary %>%
        filter(!hidden_pa_img_type %in% c('all_pa',
                                          'near_far_combined')) %>%
        filter(condition == 'schema_6_0') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                condition),
                    names_from = hidden_pa_img_type,
                    values_from = block_2_mouse_error_mean) %>% 
        mutate(far_minus_near = far - near) %>%
        select(far_minus_near) %>% .[[1]]


null_interval <- c(0,Inf)

bf_schema_6_0_far_vs_near <- reportBF(ttestBF(
        data_for_bf_schema_6_0_far_vs_near,
        nullInterval = null_interval
)[1],4)

```

```{r bayes-analysis-schema-c-far-vs-near-LOG}

data_for_bf_schema_6_0_far_vs_near_LOG <- data_summary %>%
        filter(!hidden_pa_img_type %in% c('all_pa',
                                          'near_far_combined')) %>%
        filter(condition == 'schema_6_0') %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                condition),
                    names_from = hidden_pa_img_type,
                    values_from = block_2_mouse_error_mean_LOG) %>% 
        mutate(far_minus_near = far - near) %>%
        select(far_minus_near) %>% .[[1]]


null_interval <- c(0,Inf)

bf_schema_6_0_far_vs_near_LOG <- reportBF(ttestBF(
        data_for_bf_schema_6_0_far_vs_near_LOG,
        nullInterval = null_interval
)[1],4)

```


# Reaction times 

## Comparing conditions 

```{r rt-diff-conditions}

data_summary %>%
        filter(!hidden_pa_img_type %in% c('all_pa',
                                          'near_far_combined')) %>%
        droplevels() %>%
        
        ggplot(aes(x=condition,
                   y=block_2_rt_mean)) +
        geom_violin() +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_jitter(height = 0,
                    width = 0.06,
                    alpha = 0.3) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2 RT, comparing conditions')

```

```{r rt-conditions-near-far}

data_summary %>%
        filter(!hidden_pa_img_type %in% c('all_pa',
                                          'near_far_combined')) %>%
        droplevels() %>%
        
        pivot_wider(id_cols = c(ptp,
                                counterbalancing,
                                condition),
                    names_from = hidden_pa_img_type,
                    values_from = block_2_rt_mean) %>% 
        mutate(far_minus_near = far - near) %>%
        
        ggplot(aes(x=condition,
                   y=far_minus_near)) +
        geom_violin() +
        geom_boxplot(width=0.1,
                     fatten=4,
                     outlier.shape = '') +
        geom_jitter(height = 0,
                    width = 0.06,
                    alpha = 0.3) +
        stat_summary(fun=mean,
                     color='red',
                     size=1) +
        ggtitle('Block 2 RT, comparing conditions, Far-Near') +
        geom_hline(yintercept = 0, linetype = 'dashed')

```

